
typeannot: ":" type

type:  simpletype
      | tracetype
      | hypertracetype
      | usertype
tracetype: "[" _traceelemtype ["," _traceelemtype]* "]"
_traceelemtype: simpletype | usertype

hypertracetype: "{" tracetype ["," tracetype]* "}"

!simpletype:  "Int8" | "Int16" | "Int32" | "Int64"
            | "UInt8" | "UInt16" | "UInt32" | "UInt64"
            | "Float32" | "Float64"
            | "Char" | "Bool"
!usertype: NAME

%import common.CNAME -> NAME
